jenkins:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
    io.rancher.container.create_agent: "true"
    io.rancher.container.agent.role: environment
  ports:
    - 8000:8080
  image: 172.22.101.100:5000/jenkins:latest
  tty: true
  stdin_open: true
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
